// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef main_win_h
#define main_win_h
#include <FL/Fl.H>
void Exit_CB(Fl_Widget*,void*);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *text1;
void About_CB(Fl_Widget*,void*);
extern void main_window_exit_CB(Fl_Double_Window*, void*);
#include <FL/Fl_Button.H>
extern void Capture_CB(Fl_Button*, void*);
#endif
