// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "main_win.h"
#include<stdlib.h>
#include<stdio.h>

void Exit_CB(Fl_Widget*,void*) {
  exit(0);
}

Fl_Text_Display *text1=(Fl_Text_Display *)0;

void About_CB(Fl_Widget*,void*) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(447, 343, "About");
    w = o;
    o->box(FL_PLASTIC_UP_BOX);
    o->color((Fl_Color)16);
    { text1 = new Fl_Text_Display(20, 20, 410, 290);
    } // Fl_Text_Display* text1
    o->end();
  } // Fl_Double_Window* o
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(856, 621, "Face Authentication System");
    w = o;
    o->callback((Fl_Callback*)main_window_exit_CB);
    { Fl_Button* o = new Fl_Button(20, 515, 100, 60, "Train Face");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)Exit_CB);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(155, 515, 100, 60, "Authenticate");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)Exit_CB);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(730, 515, 100, 60, "Exit");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)Exit_CB);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(455, 515, 100, 60, "Help");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)About_CB);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(145, 390, 175, 35, "Capture Face Form Cam");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)Capture_CB);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(595, 515, 100, 60, "About");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)About_CB);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(625, 355, 130, 35, "Accept ");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)Capture_CB);
    } // Fl_Button* o
    { Fl_Text_Display* o = new Fl_Text_Display(555, 15, 255, 35);
      o->box(FL_PLASTIC_UP_FRAME);
      o->color((Fl_Color)17);
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(285, 515, 130, 60, "Recognise Person");
      o->tooltip("Reconises the face of the person if the system is trained for that face");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)132);
      o->selection_color((Fl_Color)131);
      o->callback((Fl_Callback*)Exit_CB);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
