/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PROJECT1_PRIVATE_H
#define PROJECT1_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.3.2"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	3
#define VER_BUILD	2
#define COMPANY_NAME	"TECHNO INDIA, SALTLAKE, KOLKATA"
#define FILE_VERSION	"1.342"
#define FILE_DESCRIPTION	"FACE RECOGNITION SYSTEM USING LBP"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"TECHNO INDIA"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"FACE RECOGNITION SYSTEM"
#define PRODUCT_VERSION	"1.132"

#endif /*PROJECT1_PRIVATE_H*/
