// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef recognition_h
#define recognition_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Progress.H>
#endif
