// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "train_window.h"

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(650, 356, "Train faces");
    w = o;
    o->selection_color((Fl_Color)128);
    o->labelsize(16);
    { Fl_Button* o = new Fl_Button(380, 300, 135, 30, "Submit");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->color((Fl_Color)91);
      o->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Button* o
    { Fl_Input* o = new Fl_Input(190, 297, 140, 38, "ENTER NAME FOR USER");
      o->color((Fl_Color)246);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(9);
      o->labelcolor(FL_GRAY0);
    } // Fl_Input* o
    { Fl_Text_Display* o = new Fl_Text_Display(10, 35, 625, 245, "INSTRUCTIONS");
      o->box(FL_PLASTIC_UP_FRAME);
      o->color((Fl_Color)26);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelfont(9);
      o->labelsize(18);
      o->labelcolor(FL_GRAY0);
    } // Fl_Text_Display* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
